### ISSUE TITLE
Doesn't work for cloudflare tunnels

### ISSUE THREAD

**Issue by milindpatel63** [Desuuuu/traefik-cloudflare-plugin#1]
In case of cloudflare tunnel, all requests seems to be coming from 127.0.0.1 if the tunnel is running on the same machine as traefik.

Due to this this plugin doesn't work. I have to add "127.0.0.1/0" as trusted cidr in this plugin, but that defeats the purpose of checking external IP, since all requests will be from localhost.

Any way to workaround this?

**Comment by Desuuuu** [comment]
The traffic coming through the tunnel is only coming from Cloudflare, so there's no point trying to filter it based on the source IP.

In this case, using a `/0` CIDR is the proper solution if you want to use this plugin to rewrite the `X-Forwarded-For` header.

**Comment by milindpatel63** [comment]
yeah, seems reasonable.
i still wanted to block access to all other ip's except cloudflare if someone connects to my traefik instance directly.
I'm in a cgnat situation, so my server is not accessible publically. But still there are some ways like hole punching nd stuff.

I just want only cloudflare ip's and my local subnet to be able to access my traefik instance.

i do have made UFW rules to only allow access to traefik from local network. I guess that would be sufficient.
